project_id = "lgdrrlrzcoedozfjwjnr"

[functions.payment-initialize]
verify_jwt = true

[functions.payment-webhook]
verify_jwt = false

[functions.escrow-release]
verify_jwt = true

[functions.payout-withdraw]
verify_jwt = true