project_id = "lgdrrlrzcoedozfjwjnr"

[functions.notify-admin-new-jobs]
verify_jwt = false

[functions.payment-initialize]
verify_jwt = true

[functions.payment-manual-initialize]
verify_jwt = true

[functions.payment-proof-submit]
verify_jwt = true

[functions.payment-proof-verify]
verify_jwt = true

[functions.payment-webhook]
verify_jwt = false

[functions.escrow-release]
verify_jwt = true

[functions.payout-withdraw]
verify_jwt = true

[functions.job-scraper]
verify_jwt = false

[functions.send-transaction-email]
verify_jwt = false